[package]
name = "candao"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
ic-cdk = "0.3.2"
ic-cdk-macros = "0.3.2"
candid = "0.7.8"
